version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.2-java8
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - local.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - local.env

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - local.env

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - local.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - local.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - local.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.2-java8
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - local.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
